version: "3.8"

services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U symfony -d app"]
      interval: 5s
      timeout: 3s
      retries: 20

  php:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_ENV: dev
      # Symfony lira ça en priorité par rapport au .env local :
      DATABASE_URL: "pgsql://symfony:symfony@db:5432/app?serverVersion=17&charset=utf8"
      CORS_ALLOW_ORIGIN: "^https?://(localhost|127\\.0\\.0\\.1)(:[0-9]+)?$"
      APACHE_DOCUMENT_ROOT: /var/www/html/public
    volumes:
      - ./:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:80"
    command: ["/usr/local/bin/entrypoint.sh"]

  pgadmin:
    image: dpage/pgadmin4:7
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.test
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  dbdata:
