nelmio_cors:
  defaults:
    allow_origin: ['http://localhost:8081', 'http://127.0.0.1:8081']
    allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
    allow_headers: ['Content-Type', 'Authorization']
    expose_headers: []
    max_age: 3600
    allow_credentials: false
  paths:
    '^/api/': ~
