# backend/config/packages/security.yaml
security:
  password_hashers:
    App\Entity\User: 'auto'

  providers:
    app_user_provider:
      entity: { class: App\Entity\User, property: email }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    # ⬇️ Firewall de login (DOIT être avant "api")
    login:
      pattern: ^/api/auth
      stateless: true
      provider: app_user_provider
      json_login:
        check_path: /api/auth/login     # <-- on POST ici
        username_path: email
        password_path: password
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure

    # ⬇️ Firewall JWT pour toutes les autres routes /api
    api:
      pattern: ^/api
      stateless: true
      provider: app_user_provider
      jwt: ~

  access_control:
    - { path: ^/api/auth/login$, roles: PUBLIC_ACCESS, methods: [POST] } # public
    - { path: ^/api/user/create$, roles: PUBLIC_ACCESS, methods: [POST] }
    - { path: ^/api, roles: IS_AUTHENTICATED_FULLY }
